# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🛠️
      labels:
        - bug
        - fix
        - issue resolved
    - title: Enhancements ✨
      labels:
        - improvement
        - optimization
        - performance
    - title: Breaking Changes 🔥
      labels:
        - breaking change
        - major update
    - title: Deprecations 🚧
      labels:
        - deprecation