import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-w-screen justify-between min-h-screen">
        <div className="flex flex-col max-w-screen-sm px-5 py-2.5 justify-between align-middle">
          {children}
        </div>
      </body>
    </html>
  )
}
